### ISSUE TITLE
Unexpected token Lexer 

### ISSUE THREAD

**Issue by peanpanther** [mohammadmusaei/AxiomScheduler#1]
Hello, please help me 

Parser Error: Unexpected token Lexer Error: Unterminated quote at column 8 in expression ['default] at column 9 in ['default]

**Comment by mohammadmusaei** [comment]
Hi

Please send me a screenshot or more details. I clone and test the project again and no error found.

**Comment by peanpanther** [comment]
Hi, i just cloned your repo and everything works perfectly. Thank you
